server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice_back
    driver-class-name: org.mariadb.jdbc.Driver
    username: acorn
    password: acorn1234

